### ISSUE TITLE
Choose scheduler backend

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-client#1]
Many options out there (python-rq, celery, etc). Let's do an investigation on which better fit our needs.

**Comment by johngian** [comment]
I suggest we close this since it looks like the first iteration is going to be based on ``APScheduler``. We can revisit it in the future according to our needs.

[1] http://apscheduler.readthedocs.org/en/latest/

**Comment by jinxcat** [comment]
No problem on closing it, as long as we *do* review suitability
