### ISSUE TITLE
Cannot run client as a web-ui dev (Valpo)

### ISSUE THREAD

**Issue by dylan-snyder** [satnogs/satnogs-client#101]
Processing dependencies for satnogsclient==0.2.5
error: Installed distribution setuptools 3.3 conflicts with requirement setuptools>=11.3
satnogs: ERROR (not running)
oggenc: no process found
rtl_fm: no process found
No config updates to processes
satnogs: ERROR (abnormal termination)

**Comment by dylan-snyder** [comment]
Accidentally pressed enter to early:
I am part of the team at Valpo working to try and make a web ui, and we're stuck on running the client still. The above is the error I get when I run a script named reset.sh that goes as such:
`python ./setup.py build
sudo python ./setup.py install
sudo supervisorctl stop satnogs
killall -9 oggenc
killall -9 rtl_fm
sudo supervisorctl reread
sudo supervisorctl start satnogs`
The above post body is the error we get when running. Thanks much.

**Comment by dylan-snyder** [comment]
Here is my repo: [link](https://github.com/dylan-snyder/satnogs-client)

**Comment by cshields** [comment]
what distro of linux is this?  try 'sudo pip install -U setuptools'

**Comment by dylan-snyder** [comment]
distro: Ubuntu 14.04
And we still received the same error. My guess is that we most likely need to work with our engineers; we think we're missing some hardware!

**Comment by cshields** [comment]
@dylan-snyder should we keep this open? If so can I arrange a time to walk through this to see where it is falling short?

**Comment by dylan-snyder** [comment]
You can go ahead and close it! Thank you!
