### ISSUE TITLE
Large Data Transfer Protocol

### ISSUE THREAD

**Issue by GVardakis** [satnogs/satnogs-client#104]
### Uplink (Ground to Satellite)
- Ground sends packets, waits for ACK for each packet. If it doesn't receive ACK in ack_timeout time, resend the packet. If after two(?) retries the ACK doesn't come, abort
- Satellite receives packet, sends ACK. If after receive_timeout since after the last received packet, the next packet doesn't arrive, abort (or resend last?) . If a packet is received invalid, it doesn't send ACK back.
### Downlik(Satellite to Ground)
- Satellite sends all packets without waiting for ACK for eack one. It waits for ACK after sending all packets. If an ACK with requests for missed packets arrives at the end from the ground, resend the lost packets
- Ground waits for all packets. If a packet is lost, adds its sequence number to the list of lost packets, and at the end it sends a packet to the Satellite requesting the lost packets. If after receive_timeout time since the last received packet, (what?)

**Comment by cshields** [comment]
@GVardakis  what would be downlinked that requires an ACK?  telemetry would be broadcast with no ACK, so I guess an ACK from uplink commands?
