### ISSUE TITLE
Misleading satnogs-poller name 

### ISSUE THREAD

**Issue by johngian** [satnogs/satnogs-client#15]

**Comment by jinxcat** [comment]
can it be written as a periodic scheduled task?

**Comment by johngian** [comment]
It is a periodic scheduled task. ``satnogs-poller`` runs like a daemon (script needs some fine-tuning) and polls as a periodic task the API.

**Comment by aincrad** [comment]
No, I meant a task that is periodically scheduled in the scheduler.

**Comment by jinxcat** [comment]
Rename this to something other than poller

**Comment by johngian** [comment]
``satnogs-poller`` should be renamed to ``satnogs-scheduler``.

**Comment by cshields** [comment]
this changed to satnogs-client in v0.3
