### ISSUE TITLE
WOD console

### ISSUE THREAD

**Issue by surligas** [satnogs/satnogs-client#170]
Hey there,

I finished the WOD mechanism in gr-satnogs. Based on the destination SSID the deframer if the incoming frame is a WOD or not. 

If it is, it send it through a separate UDP socket (default port 5023). I think this is a quite clean solution and avoids any complicated logic. So the client needs to wait for UDP packets in another socket and display the WOD data that arrive from the GNU Radio process.

**Comment by surligas** [comment]
Any progress at this @ppapadeas @ctriant @GVardakis ?

**Comment by acinonyx** [comment]
Fixed
