### ISSUE TITLE
GNU Radio flowgraph termination

### ISSUE THREAD

**Issue by surligas** [satnogs/satnogs-client#253]
With the current setup, we noticed (https://github.com/satnogs/gr-satnogs/issues/63) that some devices are not properly released. To release them the proper way, GNU Radio process waits for a sigint signal rather than sigterm.

**Comment by cshields** [comment]
Is https://github.com/satnogs/gr-satnogs/commit/c83e53f9b5a7f2d9e36c44ece77f21ad822111e8 expected to fix?

I can test for airspy and hackrf but not for another week :/

**Comment by surligas** [comment]
Yeah, if the termination signal is `SIGINT` it should be ok. For some strange reason the osmsocom block leaves the descriptors of the devices open if the process is terminated through `SIGTERM`.

**Comment by jinxcat** [comment]
Is it possible to fix the behaviour upstream? SIGTERM is the termination
signal, SIGINT is just interrupt (like pressing Ctrl-C).
