### ISSUE TITLE
need threshold-based rotator movements

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-client#269]
Marking this as a bug as it causes problems for some rotators and their controllers.

We are too aggressively making AZ/EL adjustments in the client. This has cause relay burnout in one rotator controller and we had another report of issues stemming from it last week as well.

With most yagi beamwidths still being very wide we can use a threshold based system and make the threshold a configuration item. I would suggest default be no less than 2 degrees, wind movement in a G-5500 can cause a degree shift which would trigger an over-compensation.

**Comment by csete** [comment]
Good idea!

I think you can safely set the default to 5 degrees as most commonly available UHF antennas have a 3 dB beam width > 20 degree in both planes.

**Comment by adamkalis** [comment]
Fixed by 6b6008985f4c3990604997929f18c1a82502212d
