### ISSUE TITLE
Data directory (sqlite)

### ISSUE THREAD

**Issue by alexschultze** [satnogs/satnogs-client#36]
By default the sqlite directory comes up for me as:
'/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2-py2.7.egg/satnogsclient/jobs.sqlite'

However, that folder is not writable and it fails to access the database.

**Comment by johngian** [comment]
Thanks for the feedback. Did you install the client by checking out the code and manually build and install or via pypi?

**Comment by alexschultze** [comment]
I manually have build and installed it. As a workaround I will put the sql file into the Satnogs data directory as well.

**Comment by alexschultze** [comment]
https://github.com/alexschultze/satnogs-client/commit/77c88ab6921b5e1ce025af7bbec26c76c6df8111
