### ISSUE TITLE
Network Certificate error

### ISSUE THREAD

**Issue by alexschultze** [satnogs/satnogs-client#37]
At the part where connecting to the https api, the client throws an error. It seems that python request does not approve the certification authority, from the browser its OK.

I have seen that for some reason python https does not contain any CA authorities anyway.

A dirty workaround:
response = requests.get(url, params=params, verify=False)

I quote: "Shouldn't requests/openssl already know where to find valid certs?
No. OpenSSL trusts nothing by default. Its a polar opposite of a browser's model, where nearly everything is trusted by default." (http://stackoverflow.com/questions/22027418/openssl-python-requests-error-certificate-verify-failed)

**Comment by jinxcat** [comment]
I believe in proper certificates.

We will discuss this with the network team, and hopefully correct this on the network side.

Or should it try with verify=True first and then message/complain/scream and try with verify=False?

**Comment by alexschultze** [comment]
The Certificate are ok says my browser. We have to add the startcom
certification authority I guess therefore it's not a network problem
Am 25.03.2015 00:19 schrieb "I Charitopoulos" <notifications@github.com>:

**Comment by alexschultze** [comment]
I found another description of this problem (http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror)
. Basically two clean solutions:
(1) Include certificate .pem in the request (verify=..)
(2) Install the certificate on system level

I would avoid the verify False solution.

**Comment by comzeradd** [comment]
It seems that requests doesn't include StartCom CA. We plan to upgrade our certificate class anyway, so let's see if this will the problem. I tried using [certifi](http://certifi.io) but with no luck.

```
requests.get('https://github.com/')
<Response [200]>

requests.get('https://dev.satnogs.org/')
SSLError: SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by alexschultze** [comment]
I tried several steps, including ca-certificates on my ubuntu, certifi or manually include the .pem files for StartCom in the verify="..pem" which should work, but did not work for me.

For now as an workaround:
https://github.com/alexschultze/satnogs-client/commit/30d6b4b06bafe3756b97ff36829766d2e39824ca

**Comment by alexschultze** [comment]
I have added something that should suit the theoretical workflow, however it doesnt work practically yet.  In my browser the certificate seems very reasonable, the only message concerning it is "does not have public audit records"

**Comment by comzeradd** [comment]
I dig a bit further about this issue and the problem seems to be [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). In simple words SNI is the way to have multiple SSL hosts on the same IP. That's the case with our dev instance.

So according to [requests documentation](http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors) it has SNI support only on python3. I just tried the example in above comments in a python3 shell and it worked just fine.

So the question is could we use python3 runtime for the client? :)

**Comment by alexschultze** [comment]
I think migrating python 3 is feasible, most errors pop up with the print function, which we should get rid of anyways and use loggers.

**Comment by jinxcat** [comment]
I believe we can...  and I like the idea.

But we need to check that all libraries are available for python 3. And we will have to deal with all open PRs, "freeze" the code and make the switch.


On 16 April 2015 00:04:22 EEST, alexschultze <notifications@github.com> wrote:
>I think migrating python 3 is feasible, most errors pop up with the
>print function, which we should get rid of anyways and use loggers.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/satnogs/satnogs-client/issues/37#issuecomment-93568926

--

**Comment by johngian** [comment]
+1 for python 3 (but we need to check dependency compatibility first)

**Comment by jinxcat** [comment]
From the list of required libraries:

APScheduler
SQLAlchemy
requests
validators
python-dateutil
pyephem
pytz

All of the above seem to be ok with python 3

**Comment by johngian** [comment]
Closing this one since the initial scope was the SSL cert being used in the API deployment. Let's open another issue regarding Python 3 compatibility.
