### ISSUE TITLE
WorkerFreq .. contradiction?

### ISSUE THREAD

**Issue by alexschultze** [satnogs/satnogs-client#38]
The way its currently implemented there is a logical contradiction:
You receive using rtl_fm, however you want to change frequency like with rtl_tcp, but you can not run both?

Is that so?

**Comment by alexschultze** [comment]
I See now the intention to use rigctld for controlling the receiver. (However thats not possible to combine with RTL_FM or RTL_TCP , since there momentarily is no TCP socket for controlling)

**Comment by jinxcat** [comment]
Alex,

That's exactly the part I am hoping to finish up this week.

However, I don't get your comment about momentarily having no TCP socket for controlling.

That idea is to combine both functionalities into one thread. How will there be no socket..?

Maybe I can mention you on the PR for your comments? I'd really like your input.




On 1 April 2015 01:04:49 EEST, alexschultze <notifications@github.com> wrote:
>I See now the intention to use rigctld for controlling the receiver.
>(However thats not possible to combine with RTL_FM or RTL_TCP , since
>there momentarily is no TCP socket for controlling)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/satnogs/satnogs-client/issues/38#issuecomment-88266423

--

**Comment by alexschultze** [comment]
I mean:
The RTL_FM or RTL_TCP is not compatible with RigCtlD. Now that I understand the principle with RigCtl and RotCtl I really like the idea behind that. But that leaves two options:
-For using RTL_SDR do not use RigCTL
-Or implement a RigCTL compatible interface on RTL_TCP / RTL_FM

What you mean with PR?

**Comment by johngian** [comment]
Hey @alexschultze 

FYI we are using our fork of ``rtl-sdr`` [1] in which we added custom functionality that enables us to send frequency commands via TCP socket.

[1] https://github.com/satnogs/rtl-sdr/commit/b72ab8fc83efbc2ec112154b9d1cbe2d85b1e258

**Comment by alexschultze** [comment]
I see that makes sense! 

Personally I like the idea of directly capturing the iq samples .. and you can then still decide what you want to do with it. For that purpose I started writing an client for the rtl_tcp which can capture the data and interface with it. 
https://github.com/alexschultze/satnogs-software/tree/master/simple_tcp_receiver

Therefore it would make sense to create a super-class receiver now, that later you can easily add subclasses for each type of receiving (rtl-tcp, or rtl_fm with rigctl, audio)
