### ISSUE TITLE
dummy job_id in satnogs-task is interpreted as a false in receiver.py

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-client#46]
in the latest satnogs-task:

job_id = 0 # Dummy vaule for manually triggered jobs

causes the SignalReceiver to die when 0 is interpreted as a false (job_id becomes observation_id):

        if not observation_id:
            raise LookupError('arg not found: observation_id')

Not sure if any other random ID will conflict with real jobs down the road, but changing this to 1 works for now.

/cc @johngian

**Comment by johngian** [comment]
Hey @cshields this is taken care of in this [1] PR. This is not yet merged, we are waiting for the last code review update. Since there are some minor fixes to amend I'll try to rebase and merge it ASAP. 

[1] https://github.com/satnogs/satnogs-client/pull/39

**Comment by cshields** [comment]
No need to rush it for me, I fixed it locally - just wanted to make sure it was known.

**Comment by johngian** [comment]
Fixed in #49
