### ISSUE TITLE
worker.py sends radians but rotctld expects degrees

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-client#47]
in worker.py's send_to_socket:
```
        az = p['az'].conjugate()
        alt = p['alt'].conjugate()
        msg = 'P {0} {1}\n'.format(az, alt)
```
The conjugate() function converts the az and alt to radians (also worth noting they can be represented the same as floats from the ephem module)...  However, rotctld expects degrees so the tracking is way off (in most cases just sticking around the first couple of degrees N and less than 1 EL)

The way to fix this is to convert to degrees  (import pi and take the radians * 180 / math.pi).   I added this to both lines locally and the tracker now works as it should (testing with satnogs-task).

**Comment by johngian** [comment]
Thanks @cshields for reporting that. Closing this after #48
