### ISSUE TITLE
Design instantiation of SignalSerializer objects 

### ISSUE THREAD

**Issue by papamat** [satnogs/satnogs-client#5]
We need to finalize the procedure of how to instantiate the serializer objects and how to spawn demodulation/encoding/decoding processes.

* Who is killing these processes?
* When are we closing file descriptors?
* Is rtl_fm running as daemon or we spawn/kill on each observation.

**Comment by jinxcat** [comment]
It happens via the observer.

On 11 January 2015 22:00:25 EET, Manthos Papamatthaiou <notifications@github.com> wrote:
>We need to finalize the procedure of how to instantiate the serializer
>objects and how to spawn demodulation/encoding/decoding processes.
>
>* Who is killing these processes?
>* When are we closing file descriptors?
>* Is rtl_fm running as daemon or we spawn/kill on each observation.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/satnogs/satnogs-client/issues/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by johngian** [comment]
Cool. We still need to integrate those 2 components. Closing this issue and opening a new more appropriate one.
