### ISSUE TITLE
Tag and release 0.2.4

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-client#65]
I'd recommend we push out 0.2.4 soon - first there is a bug in 0.2.3 where the recording process does not stop (this is fixed in master), and ppm is not configurable meaning the pip installed version will need a dongle with very little drift to work (I have a PR to fix this)

**Comment by johngian** [comment]
Sounds good. I merged #64 so we can tag current master as ``0.2.4`` and push latest release to pypi.

**Comment by johngian** [comment]
Done [1] and done [2] :smile:

[1] https://github.com/satnogs/satnogs-client/releases/tag/v0.2.4
[2] https://pypi.python.org/pypi/satnogsclient
