### ISSUE TITLE
Add decoding values for multimon-ng

### ISSUE THREAD

**Issue by johngian** [satnogs/satnogs-client#7]
Our current valid decoding values where taken from the manpage of ``multimon``. ``multimon-ng`` allows more types of decoding.

We need to populate ``_valid_decoding_values`` with the new ones from multimon-ng.

**Comment by jinxcat** [comment]
Where can the list of values be found?

**Comment by ppapadeas** [comment]
From dev build of multimon-ng : 

available demodulators: POCSAG512 POCSAG1200 POCSAG2400 EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV SCOPE

**Comment by ppapadeas** [comment]
Fixed
