### ISSUE TITLE
Match env variables names

### ISSUE THREAD

**Issue by comzeradd** [satnogs/satnogs-client#74]
Client [expects](https://github.com/satnogs/satnogs-client/blob/master/satnogsclient/settings.py#L15-L18) env variables to start with different prefix than the ones on error messages.

For instance, if I miss to provide `SATNOGS_STATION_ID` I get the error:

```
Exception: GROUND_STATION_ID not configured
```

which is very confusing and misleading about what I should do.

**Comment by acinonyx** [comment]
@comzeradd shall I close this one?

**Comment by comzeradd** [comment]
Is it invalid? I see we still assign env variables to different names making errors difficult for user to understand. Even on [dev branch](https://github.com/satnogs/satnogs-client/blob/dev/satnogsclient/settings.py#L16-L19)

**Comment by ppapadeas** [comment]
This is still valid

**Comment by ppapadeas** [comment]
Closed as per #234
